server:
  port: 8040

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: bd
          uri: http://www.baidu.com
          predicates:
            - Path=/bd/**
          filters:
            - StripPrefix=1
        - id: qq
          uri: http://www.qq.com
          predicates:
            - Path=/qq/**
          filters:
            - StripPrefix=1
        - id: jd
          uri: http://www.jd.com
          predicates:
            - Path=/jd/**
          filters:
            - StripPrefix=1
        
logging:
  level:
    org.springframework.cloud.gateway: debug